image: google/cloud-sdk:latest

definitions:
  steps:
    step: &release
        name: "Prepare - Deploy Site"
        script:
          - echo $PROJECT_KEYFILE > /tmp/key-file.json
          # - export NAME="fao-wapor-et-look"
          - gcloud auth activate-service-account --key-file /tmp/key-file.json
          - gcloud config set project $PROJECT_ID
          - gsutil cp -r docs/_build/html/** gs://$BUCKET_NAME/aquastat/py-wapor

          # - gcloud builds submit --tag gcr.io/$PROJECT_ID/$NAME:$BITBUCKET_BUILD_NUMBER
          # - sed -i "s/\$VERSION/$BITBUCKET_BUILD_NUMBER/g" ./cloudrun-iac.yaml
          # - sed -i "s/\$PROJECT_ID/$PROJECT_ID/g" ./cloudrun-iac.yaml
          # - sed -i "s/\$NAME/$NAME/g" ./cloudrun-iac.yaml
          # - gcloud services enable run.googleapis.com
          # - gcloud beta run services replace cloudrun-iac.yaml --platform=managed --region=europe-west3

pipelines:
  branches:
    dev:
      - step: 
          <<: *release
          deployment: review
    master:
      - step: 
          <<: *release
          deployment: prod
